const config = require('config')
const axios = require('axios')
const _ = require('lodash')
const columnify = require('columnify')
const util = require('util')
const fs = require('fs')
const chalk = require('chalk')

const configCheck = require('../helpers/configCheck')

const writeFile = util.promisify(fs.writeFile)

const buildReport = async (logs, reportDate) => {
  const mapped = logs.map(x => {
    return {
      id: x['todo-item-id'],
      projectName: x['project-name'],
      task: x['todo-item-name'],
      hours: x.hours,
      minutes: x.minutes,
      time: `${x.hours > 0 ? x.hours + 'h : ' : ''}${x.minutes}min`,
    }
  })
  const grouped = _.groupBy(mapped, 'projectName')

  const dirName = `${
    global.__basePath
  }/reports/${reportDate.getFullYear()}/${reportDate.toLocaleString('en-us', {
    month: 'short',
  })}/${reportDate.getDate()}`

  // Create directory if not exists.
  if (!fs.existsSync(dirName)) {
    fs.mkdirSync(dirName, {recursive: true})
  }

  if (grouped.length < 1) {
    return console.log(chalk.red('No entries found!!'))
  }

  for (const key of Object.keys(grouped)) {
    console.log(
      `\n\n—————————————————————— ${chalk.bgMagenta(
        `Start report of ${key}`,
      )} ——————————————————————`,
    )
    const res = await writeProjectReport(reportDate, dirName, key, grouped[key])
  }
}

const secondsToHms = d => {
  d = Number(d)
  const h = Math.floor(d / 3600)
  const m = Math.floor((d % 3600) / 60)
  const s = Math.floor((d % 3600) % 60)

  const hDisplay = h > 0 ? h + (h == 1 ? ' hour, ' : ' hours, ') : ''
  const mDisplay = m > 0 ? m + (m == 1 ? ' minute, ' : ' minutes, ') : ''
  const sDisplay = s > 0 ? s + (s == 1 ? ' second' : ' seconds') : ''
  return hDisplay + mDisplay + sDisplay
}

const minutesToDecimal = d => {
  d = Number(d)
  const h = Math.floor(d / 3600)
  const m = Math.floor((d % 3600) / 60)
  const deci = m / 60
  return (h + deci).toFixed(2)
}

const writeProjectReport = async (reportDate, dirName, project, logs) => {
  let weekDay = reportDate.toLocaleString('en-us', {weekday: 'short'})

  let sl = 1
  logs = logs.map(x => {
    x.sl = sl++
    return x
  })
  // Convert hours and minutes to second.
  const totalTime = logs.reduce((sum, log) => {
    return sum + (log.hours * 3600 + log.minutes * 60)
  }, 0)

  let txt = columnify(logs, {
    columns: ['sl', 'task', 'time'],
    config: {
      task: {
        maxWidth: 60,
      },
    },
    columnSplitter: ' | ',
  })

  const formattedTime = `${secondsToHms(totalTime)} [${minutesToDecimal(
    totalTime,
  )}]`

  const grouped = _.uniq(logs, 'id')

  const fileName = `${project}-${weekDay}-${formattedTime}.txt`.replace(
    /[/\\?%*:|"<> ]/g,
    '_',
  )

  let commitsText = ''
  const commits = await getCommits(reportDate, project)

  if (commits.length > 0) {
    commitsText = `COMMITS (${commits.length})\n---------------`
    const commitUrls = commits.map(x => x.html_url)
    commitUrls.forEach(url => {
      commitsText += `\n${url}`
    })
  }

  txt = `${reportDate.toLocaleString('en-us', {
    weekday: 'long',
  })}, ${reportDate.getDate()} ${reportDate.toLocaleString('en-us', {
    month: 'long',
  })}
Total time spent: ${formattedTime}
Worked on total ${grouped.length} tasks.
Total ${logs.length} time entries.


TASKS:
---------------
${txt}

${commitsText}

Auto generated by "Report builder".
    `
  return writeFile(`${dirName}/${fileName}`, txt, 'utf8').then(() => {
    console.log(`\n${txt}`)
    console.log('—————————————————————— End of report ——————————————————————')
    console.log(`Report file generated at ${dirName}/${fileName}`)
  })
}

const getCommits = async (reportDate, project) => {
  // If no project info then return.
  if (
    !config.projects[project] ||
    !config.projects[project].repos ||
    config.projects[project].repos.length === 0
  ) {
    return []
  }

  const projectInfo = config.projects[project]
  const until = new Date(reportDate.toISOString())

  const params = {
    since: reportDate.toISOString(),
    until: until.setUTCHours(24, 0, 0, 0),
  }

  let allCommits = []

  for (const repo of projectInfo.repos) {
    try {
      const {data} = await axios.get(
        `https://api.github.com/repos/lattepress/${repo}/commits`,
        {
          params,
          auth: {
            username: config.github_username,
            password: config.github_token,
            author: config.github_username,
          },
        },
      )

      allCommits = allCommits.concat(data)
    } catch (err) {
      console.log(err)
    }
  }

  return allCommits
}

module.exports = async (date = false) => {
  if (configCheck() === false) {
    return console.log(chalk.red('Required config missing!'))
  }

  let reportDate = new Date()
  if (!date) {
    reportDate.setUTCHours(0, 0, 0, 0)
    reportDate.setDate(reportDate.getDate() - 1)
    const yesterday = reportDate.toISOString().split('T')[0]
    date = yesterday
  } else {
    reportDate = new Date(date)
  }

  console.log(chalk.bgGreen(`\n\n\n   Generating report for : ${date}   `))
  try {
    const {data} = await axios.get(
      'https://codeninjas.teamwork.com/time_entries.json',
      {
        params: {
          fromdate: date,
          todate: date,
        },
        auth: {
          username: config.email,
          password: config.password,
        },
      },
    )

    if (data.STATUS != 'OK') {
      return console.log(
        chalk.bgRed(
          `Something went wrong, fetching time log failed. Status: ${data.STATUS}`,
        ),
      )
    }

    if (data['time-entries'].length === 0) {
      return console.log(chalk.bgRed('No time entries found for this day!!'))
    }

    console.log(
      chalk.bgBlue(`Total ${data['time-entries'].length} time entries found.`),
    )
    await buildReport(data['time-entries'], reportDate)
    console.log(`\n\nHappy coding!!`)
  } catch (err) {
    console.log(`Failed to get time log entry from TeamWork`)
    return console.log(err)
  }

  console.log(
    chalk.blue(
      `Let me know if you have any suggestions or found any errors at rah12@live.com — Rahul Aryan`,
    ),
  )
}
